sauce_username: timestamp-nano
name: timestamp-nano
ui: mocha-bdd
html: "test/zuul/zuul.html"
browsers:
  - name: ie
    version: "9..latest"
  - name: chrome
    version: "latest"
  - name: firefox
    version: "latest"
  - name: safari
    version: "latest"
  - name: iphone
    version: ["8.4", "9.3", "10.3..latest"]
  - name: android
    version: ["4.4", "5.1", "6.0..latest"]
